### PR TITLE
added 2012 Ohio presidential results

### PR DESCRIPTION
**Pull request by hodgesmr**
I decided to take a crack at the Ohio 2012 Presidential results.

I grabbed the data from [here](http://www.sos.state.oh.us/SOS/elections/Research/electResultsMain/2012Results.aspx).

I based the CSV format off what I saw on others. Let me know if I messed something up.

Question 1: there were lots of parties reported from the Ohio SoS file, but other CSVs only seemed to record: `D`, `L`, `R`, and `N`. I didn't know what `N` was, so I left it out. I can update as needed. What about the other reported parties? I can update for those too if desired.

I didn't know how to fill in `district` so that's blank. Let me know if that's something I should have.

This is my first PR to this organization, so throw any and all feedback at me!

### CODE REVIEW

**Comment by dwillis** [comment]
Thanks for this, @hodgesmr! A couple of notes: `district` would be blank for the presidential race, so there's no value for it. If it's possible, please include whatever party value the state data has (N is probably Natural Law). 

Are you willing/interested to do county-level results for other offices for 2012?

**Comment by hodgesmr** [comment]
> `district` would be blank for the presidential race

Makes sense. I assume this refers to congressional district for relevant races?

> please include whatever party value the state data has

Will do. Is there a standard format? The source data has the full party name. Just use first letter?

> Are you willing/interested to do county-level results for other offices for 2012? 

Yes! I thought I'd try this one first and see how difficult it would be (not too bad with Ohio's XLSX data!) I can probably get more offices in here too.

**Comment by dwillis** [comment]
Congressional district and also state legislative districts, yes. For parties, you can use the full name in the source data. Thanks!

**Comment by hodgesmr** [comment]
Added the full party names.

I think I'll take this one file at a time, since I haven't yet determined my cadence here. This way there can be some data pushed up as I go.

**Pull request merged**
