### PR TITLE
53: County-level results for 2008 general and primary elections

### PR DESCRIPTION
**Pull request by christopherjenness**
Still working on this.  Haven't done primaries, but should go quickly.

I didn't scrape the district numbers for each county.  Can I just get them by joining data from a different year? Or do the discrict/county relationship change between years?

### CODE REVIEW

**Comment by dwillis** [comment]
I'll need to gather those since the current file is for 2010+ districts.

**Comment by christopherjenness** [comment]
For the republican presidential primaries, there are two separate links (that contain different numbers): "District Totals" and "At-Large".

https://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2008ElectionResults/prpresdistrict.aspx

https://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2008ElectionResults/prpresal.aspx

What is the difference, and which one is correct?

**Comment by christopherjenness** [comment]
I added the primary election results.  Still need to look over it and also add the district numbers.  If it is too much of a hassle for you to get them, I can scrape them.  Let me know.

**Comment by dwillis** [comment]
Fun fact about Ohio GOP: presidential primaries consist of two votes on the same day - one in which voters vote for a statewide (at-large) nominee and another in which they choose a nominee from their congressional district. Usually it's the same person, but there are two sets of results. At-large has no district value, like regular presidential results, but the CD-based ones get a district value. Make sense?

**Comment by christopherjenness** [comment]
Oh interesting.  That's really weird, though.  What's the purpose? 

So you want both data sets scraped?  If so, how to label them?

**Comment by dwillis** [comment]
The purpose was back when Ohio used to elect an at-large congressman (seriously). It's weird. So yes, we should have both. Label them normally, but the CD-based results get a value for district.

**Comment by christopherjenness** [comment]
Did you happen to gather the district-county 2008 relationship data? If not no worries, I'll scrape it from the data.

**Comment by dwillis** [comment]
I haven't, no, so that would be great. Thanks!

**Comment by christopherjenness** [comment]
I think I've finished this.

I guess I don't understand what a district is.  I thought a county belonged to a district.  But some counties belong to two districts?

For anything that had an associated district, I put that district in the csv.   If it didn't have a district (Republican President At-large), district is left blank.

**Comment by dwillis** [comment]
Thanks, @christopherjenness! A congressional district can cross county boundaries, and some counties have parts of multiple districts.

**Pull request merged**
