### PR TITLE
48: 2012 Precinct

### PR DESCRIPTION
**Pull request by christopherjenness**
I had a hard time with your scripts, so I just wrote something else real quick.  This still needs some work, but would you mind looking at it, and seeing what needs to be done?  The file is `20121106__oh__general__precinct.csv`.  

The things I see are: 

- Candidate names are LAST, FIST.  Does this need to be switched around?
- For some reason, the original file didn't have district numbers for US Senate Data.  Does this need to be added to the CSV file?

Anything else?

### CODE REVIEW

**Comment by dwillis** [comment]
This looks good - the only things I see are that the column names (county & precinct) don't seem to match the data, they look reversed. US Senate has no district, so that's fine. And some of the candidate names have a leading space.

**Comment by christopherjenness** [comment]
Thanks! I'll make those changes.

**Comment by christopherjenness** [comment]
I've removed leading/lagging spaces from candidates.  I don't see where the county and precinct are reversed.  For example, the first row county='Hamilton', precinct='CHEVOIT 1-A'.  I looked through and coun't find where else it might be reversed.  I'm probably misunderstanding something, though.

**Comment by dwillis** [comment]
Ah, yes, my mistake. Looks great, thanks!

**Pull request merged**
